lang:
  default: ja
  e: en
message:
  ja:
    sitename: 蘭裕園
    tagline: エビネとウチョウランの専門農園
    keywords: エビネ, ウチョウラン
  en:
    sitename: Ranyuen
    tagline: Nurcery for Japanese Orchids
    keywords: Japanese Orchids, Calanthe, Ponerorchis
redirect:
  "/index.html": "/"
  "/cal/cal.html": "/calanthe/"
  "/cal/cal_fun.html": "/calanthe/"
  "/cal/cal_coffee.html": "/calanthe/info_coffeecup_calanthe"
  "/pone/pone.html": "/ponerorchis/"
  "/pone/pone_fun.html": "/ponerorchis/"
  "/sai/sai_first.html": "/calanthe/"
  "/sai/sai_kan.html": "/calanthe/cultivation/tech_to_grow_calanthe_for_beginner"
  "/sai/sai_type.html": "/calanthe/grouping/info_types_of_calanthe"
  "/sai/sai_jiebine.html": "/calanthe/grouping/info_about_JIEBINE_calanthe_discolor"
  "/sai/sai_spring.html": "/calanthe/cultivation/growings_calanthe_in_each_season"
  "/sai/sai_summer.html": "/calanthe/cultivation/growings_calanthe_in_each_season"
  "/sai/sai_autumn.html": "/calanthe/cultivation/growings_calanthe_in_each_season"
  "/sai/sai_winter.html": "/calanthe/cultivation/growings_calanthe_in_each_season"
  "/sai/sai_kabu.html": "/calanthe/cultivation/repot_calanthe"
  "/sai/sai_zisei.html": "/calanthe/info_lerning_calanthe_from_territory"
  "/sai/sai_fertilizer.html": "/calanthe/cultivation/fertilizing_for_calanthe"
  "/sai/sai_cultivation.html": "/calanthe/cultivation/growings_calanthe_in_a_pot"
  "/sai/sai_garden.html": "/calanthe/cultivation/growings_calanthe_on_a_garden"
  "/sai/sai_byougai.html": "/calanthe/cultivation/controlling_pests_of_calanthe"
  "/sai2/sai2_first.html": "/ponerorchis/"
  "/sai2/sai2_pon.html": "/ponerorchis/"
  "/sai2/sai2_mmrr.html": "/ponerorchis/as_miniminiranran"
  "/sai2/sai2_kan.html": "/ponerorchis/cultivation/"
  "/sai2/sai2_usai.html": "/ponerorchis/cultivation/special_upbringing_of_ponerorchis"
  "/sai2/sai2_zyou.html": "/ponerorchis/cultivation/special_upbringing_of_ponerorchis"
  "/sai2/sai2_u.html": "/ponerorchis/kind_of_ponerorchis"
  "/sai2/sai2_a.html": "/ponerorchis/kind_of_ponerorchis"
  "/sai2/sai2_k.html": "/ponerorchis/kind_of_ponerorchis"
  "/sai2/sai2_s.html": "/ponerorchis/kind_of_ponerorchis"
  "/sai2/sai2_h.html": "/ponerorchis/kind_of_ponerorchis"
  "/sai2/sai2_n.html": "/ponerorchis/kind_of_ponerorchis"
  "/sai2/sai2_ti.html": "/ponerorchis/kind_of_ponerorchis"
  "/sai2/sai2_ta.html": "/ponerorchis/"
  "/sai2/sai2_zisei.html": "/ponerorchis/habitat_of_ponerorchis"
  "/sai2/sai2_mi.html": "/ponerorchis/cultivation/"
  "/sai2/sai2_mo.html": "/ponerorchis/cultivation/"
  "/sai2/sai2_miz.html": "/ponerorchis/special_upbringing_of_ponerorchis"
  "/sai2/sai2_ya.html": "/ponerorchis/special_upbringing_of_ponerorchis"
  "/sai2/sai2_kaika.html": "/ponerorchis/cultivation/"
  "/sai2/sai2_byougai.html": "/ponerorchis/controlling_pests_of_ponerorchis"
  "/sai3/": "/calanthe/recent_failure_and_provision"
  "/guide/guide.html": "/about_us/"
  "/guide/guide_dvd.html": "/about_us/"
  "/guide/guide_2012.html": "/about_us/"
  "/guide/guide_2011.html": "/about_us/"
  "/guide/guide_2010.html": "/about_us/"
  "/guide/guide_ranyuen.html": "/about_us/"
  "/guide/guide_access.html": "/about_us/direction"
  "/guide/guide_book.html": "/calanthe/"
  "/guide/guide_wanted.html": "/about_us/"
  "/e": "/en/"
  "/e/": "/en/"
  "/e/cal/cal_lady.html": "/en/calanthe/cultivation/tech_to_grow_calanthe_for_beginner"
  "/e/cal/cal_pro.html": "/en/calanthe/cultivation/tech_to_grow_calanthe_for_beginner"
  "/e/cal/cal.html": "/en/calanthe/cultivation/tech_to_grow_calanthe_for_beginner"
  "/e/cal/cal_mus.html": "/en/calanthe/cultivation/tech_to_grow_calanthe_for_beginner"
  "/e/cal/cal_spring.html": "/en/calanthe/cultivation/tech_to_grow_calanthe_for_beginner"
  "/e/cal/cal_fun.html": "/en/calanthe/cultivation/tech_to_grow_calanthe_for_beginner"
  "/e/e/pone.html": "/en/ponerorchis/tech_to_grow_ponerorchis_01_for_beginner"
  "/e/e/index.html": "/en/"
  "/cal_bloom.html": "/calanthe/"
  "/e/cal/cal_full.html": "/en/calanthe/cultivation/tech_to_grow_calanthe_for_beginner"
  "/e/cal/cal_blo.html": "/en/calanthe/cultivation/tech_to_grow_calanthe_for_beginner"
  "/e/cal/cal_oji.html": "/en/calanthe/cultivation/tech_to_grow_calanthe_for_beginner"
  "/e/cal/cal_haru.html": "/en/calanthe/cultivation/tech_to_grow_calanthe_for_beginner"
  "/pone.html": "/ponerorchis/"
